/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Daniel
 */
public class Detenue extends javax.swing.JFrame {

    /**
     * Creates new form Detenue
     */
    Controlleur.Codes cd = new Controlleur.Codes();

    public Detenue() {
        initComponents();
        Image icon = new ImageIcon(this.getClass().getResource("/B2.PNG")).getImage();
        this.setIconImage(icon);
        cd.chargementcomboxAgent(agent);
        cd.chargementcomboxCellule(cellule);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        re = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnAnnuler = new javax.swing.JButton();
        txtNom = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtLieu = new javax.swing.JTextField();
        txtPrenom = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtProfession = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtMotif = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtOrigine = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        ajouter = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        dateSortie = new com.toedter.calendar.JDateChooser();
        naiss = new com.toedter.calendar.JDateChooser();
        etat = new javax.swing.JComboBox<>();
        agent = new javax.swing.JComboBox<>();
        cellule = new javax.swing.JComboBox<>();
        genre = new javax.swing.JComboBox<>();
        IdAgent = new javax.swing.JLabel();
        IdCellule = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Nouveau detenue");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 8, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 644, 10));

        re.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        re.setForeground(new java.awt.Color(255, 255, 255));
        re.setText("RE");
        jPanel1.add(re, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 40, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 51));
        jLabel11.setText("Date de Naissance");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 133, -1, -1));

        btnAnnuler.setBackground(new java.awt.Color(153, 0, 0));
        btnAnnuler.setForeground(new java.awt.Color(255, 255, 255));
        btnAnnuler.setText("Annuler");
        btnAnnuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnnulerMouseClicked(evt);
            }
        });
        jPanel1.add(btnAnnuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, -1, -1));
        jPanel1.add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 162, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 51));
        jLabel15.setText("Nom");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 51));
        jLabel16.setText("Lieu de Naissance");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));
        jPanel1.add(txtLieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 162, -1));
        jPanel1.add(txtPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 162, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 51));
        jLabel17.setText("Prenom");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 51));
        jLabel18.setText("Genre");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 51));
        jLabel14.setText("Profession");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 194, -1, -1));

        txtProfession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessionActionPerformed(evt);
            }
        });
        jPanel1.add(txtProfession, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 162, -1));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 51, 51));
        jLabel19.setText("Motif Incarseration");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));
        jPanel1.add(txtMotif, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 162, -1));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 51, 51));
        jLabel20.setText("Etat");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 51, 51));
        jLabel22.setText("Date de Sortie prevue");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, -1));

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 51, 51));
        jLabel23.setText("Cellule");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        txtOrigine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrigineActionPerformed(evt);
            }
        });
        jPanel1.add(txtOrigine, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 170, -1));

        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 51, 51));
        jLabel26.setText("Origine");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        jLabel27.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 51, 51));
        jLabel27.setText("Nom Agent");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, -1, -1));

        ajouter.setBackground(new java.awt.Color(0, 51, 51));
        ajouter.setForeground(new java.awt.Color(255, 255, 255));
        ajouter.setText("Ajouter");
        ajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajouterMouseClicked(evt);
            }
        });
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });
        jPanel1.add(ajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, -1, -1));

        jLabel24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons8-add-30 (1).png"))); // NOI18N
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        dateSortie.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(dateSortie, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 170, 30));

        naiss.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(naiss, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 160, 30));

        etat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MARIE", "CELEBATAIRE", "DIVORCE", "VEUVE" }));
        jPanel1.add(etat, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 170, 30));

        jPanel1.add(agent, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 170, 30));

        jPanel1.add(cellule, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 170, 30));

        genre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        jPanel1.add(genre, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 170, 30));

        IdAgent.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(IdAgent, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 70, 30));

        IdCellule.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(IdCellule, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*    public void Clear(){
        txtRE.setText("");
        txtNom.setText("");
        txtNaissance.setText("");
        txtPrenom.setText("");
        txtEntree.setText("");
        txtMotif.setText("");
        txtID_Agent.setText("");
        txtGenre.setText("");
        txtSortie.setText("");
        txtID_cellule.setText("");
        txtProfession.setText("");
        txtLieuNaissance.setText("");
        txtEtat.setText("");
        txtGenre.setText("");
    }
    
     */
    private void ajouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouterMouseClicked

        // TODO add your handling code here:
        /*Prisonnierc p1 = new Prisonnierc();
        p1.setRE(txtRE.getText());
        p1.setNom(txtNom.getText());
        p1.setPrenom(txtPrenom.getText());
        p1.setDateNaissance(txtNaissance.getText());
        p1.setLieuNaissance(txtLieuNaissance.getText());
        p1.setGenre(txtGenre.getText());
        p1.setProfession(txtProfession.getText());
        p1.setDateEntree(txtEntree.getText());
        p1.setDateSortie(txtSortie.getText());
        p1.setEtat(txtEtat.getText());
        p1.setIdCellule(Integer.parseInt(txtID_cellule.getText()));
        p1.setIdAgent(Integer.parseInt(txtID_Agent.getText()));
        p1.setOrigine(txtOrigine.getText());
        
        PrisonnierImplementDAO newpri = new PrisonnierImplementDAO();
        newpri.ajouter(p1);
        Clear();
        fermer();
         */
    }//GEN-LAST:event_ajouterMouseClicked

    private void btnAnnulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnnulerMouseClicked
        fermer();
    }//GEN-LAST:event_btnAnnulerMouseClicked

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        cd.getIdCellule(IdCellule, cellule);
        cd.getIdAgent(IdAgent, agent);
        cd.InsertDetenu(re, IdCellule, IdAgent, txtNom, txtPrenom, etat, txtProfession, cellule, genre, txtLieu, txtOrigine, dateSortie, naiss, txtMotif);
        
        fermer();
    }//GEN-LAST:event_ajouterActionPerformed

    private void txtOrigineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrigineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrigineActionPerformed

    private void txtProfessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfessionActionPerformed

    void fermer() {
        Listedetenue d = new Listedetenue();
        d.setVisible(true);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Detenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Detenue().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IdAgent;
    private javax.swing.JLabel IdCellule;
    private javax.swing.JComboBox<String> agent;
    private javax.swing.JButton ajouter;
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JComboBox<String> cellule;
    private com.toedter.calendar.JDateChooser dateSortie;
    private javax.swing.JComboBox<String> etat;
    private javax.swing.JComboBox<String> genre;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JDateChooser naiss;
    private javax.swing.JLabel re;
    private javax.swing.JTextField txtLieu;
    private javax.swing.JTextField txtMotif;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtOrigine;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtProfession;
    // End of variables declaration//GEN-END:variables
}
