/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.Image;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Daniel
 */


public class Home extends javax.swing.JFrame {

    Color pasedefault;
    Color paseClick;
    public Home() {
        initComponents();
        
        Image icon = new ImageIcon(this.getClass().getResource("/B2.PNG")).getImage();
        this.setIconImage(icon);
        this.setTitle("Prison System Management");
        
        pasedefault = new Color(0,51,51);
        paseClick = new Color(204,204,204);
        pane1.setBackground(paseClick);
        pane2.setBackground(pasedefault);
        pane3.setBackground(pasedefault);
        pane4.setBackground(pasedefault);
        pane5.setBackground(pasedefault);
        
        datecourante();
        
        Dashbord dash = new Dashbord();
        jDesktopPane1.add(dash).setVisible(true);
    }

        // methode pour la recuperation  de la date et l'heure courante
    public void datecourante() {
        Thread clock = new Thread() {
            public void run() {
                for (;;) {
                    Calendar Cal = new GregorianCalendar();

                    int sconde = Cal.get(Calendar.SECOND);
                    int minute = Cal.get(Calendar.MINUTE);
                    int heure = Cal.get(Calendar.HOUR);
                    int AM_PM = Cal.get(Calendar.AM_PM);  
                    String pa;
                    if(AM_PM==1){
                        pa="PM";
                    }else{
                        pa="AM";
                    }
                    
                         
                    lab_heure.setText( + heure + ":" + (minute) + ":" + sconde +" "+pa  );
                    
                 int mois = Cal.get(Calendar.MONTH);
                    int annee = Cal.get(Calendar.YEAR);
                    int jour = Cal.get(Calendar.DAY_OF_MONTH);

                    lab_date.setText( + jour + "/" + (mois+1) + "/" + annee);              
                    
                    
                    try {
                        sleep(1000);

                    } catch (InterruptedException ex) {
                        Logger.getLogger(Calendar.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            }

        };
        
clock.start();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lab_heure = new javax.swing.JLabel();
        lab_date = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnDashbord = new javax.swing.JPanel();
        pane1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnListdetenue = new javax.swing.JPanel();
        pane2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnListvisite = new javax.swing.JPanel();
        pane3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnListbatiment = new javax.swing.JPanel();
        pane4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btnListcellule = new javax.swing.JPanel();
        pane5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lab_heure.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lab_heure.setForeground(new java.awt.Color(255, 255, 255));
        lab_heure.setText("02:27:40 AM");
        jPanel3.add(lab_heure, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 80, -1));

        lab_date.setBackground(new java.awt.Color(102, 102, 102));
        lab_date.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lab_date.setForeground(new java.awt.Color(255, 255, 255));
        lab_date.setText("01/12/2011");
        jPanel3.add(lab_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 740, 30));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Master Liste");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 262, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons8-disconnect-17.png"))); // NOI18N
        jLabel13.setText("Deconnexion");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, -1));

        btnDashbord.setBackground(new java.awt.Color(0, 51, 51));
        btnDashbord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashbordMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDashbordMousePressed(evt);
            }
        });

        pane1.setPreferredSize(new java.awt.Dimension(5, 0));

        javax.swing.GroupLayout pane1Layout = new javax.swing.GroupLayout(pane1);
        pane1.setLayout(pane1Layout);
        pane1Layout.setHorizontalGroup(
            pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pane1Layout.setVerticalGroup(
            pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons8-monitor-16.png"))); // NOI18N
        jLabel14.setText("Dashbord");

        javax.swing.GroupLayout btnDashbordLayout = new javax.swing.GroupLayout(btnDashbord);
        btnDashbord.setLayout(btnDashbordLayout);
        btnDashbordLayout.setHorizontalGroup(
            btnDashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDashbordLayout.createSequentialGroup()
                .addComponent(pane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel14)
                .addGap(0, 61, Short.MAX_VALUE))
        );
        btnDashbordLayout.setVerticalGroup(
            btnDashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDashbordLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        jPanel1.add(btnDashbord, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 102, -1, -1));

        btnListdetenue.setBackground(new java.awt.Color(0, 51, 51));
        btnListdetenue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListdetenueMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListdetenueMousePressed(evt);
            }
        });

        pane2.setPreferredSize(new java.awt.Dimension(5, 0));

        javax.swing.GroupLayout pane2Layout = new javax.swing.GroupLayout(pane2);
        pane2.setLayout(pane2Layout);
        pane2Layout.setHorizontalGroup(
            pane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pane2Layout.setVerticalGroup(
            pane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons8-user-16.png"))); // NOI18N
        jLabel15.setText("Liste Detenue");

        javax.swing.GroupLayout btnListdetenueLayout = new javax.swing.GroupLayout(btnListdetenue);
        btnListdetenue.setLayout(btnListdetenueLayout);
        btnListdetenueLayout.setHorizontalGroup(
            btnListdetenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListdetenueLayout.createSequentialGroup()
                .addComponent(pane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel15)
                .addGap(0, 41, Short.MAX_VALUE))
        );
        btnListdetenueLayout.setVerticalGroup(
            btnListdetenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListdetenueLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        jPanel1.add(btnListdetenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 146, -1, -1));

        btnListvisite.setBackground(new java.awt.Color(0, 51, 51));
        btnListvisite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListvisiteMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListvisiteMousePressed(evt);
            }
        });

        pane3.setPreferredSize(new java.awt.Dimension(5, 0));

        javax.swing.GroupLayout pane3Layout = new javax.swing.GroupLayout(pane3);
        pane3.setLayout(pane3Layout);
        pane3Layout.setHorizontalGroup(
            pane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pane3Layout.setVerticalGroup(
            pane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons8-list-16 (1).png"))); // NOI18N
        jLabel16.setText("Liste Visite");

        javax.swing.GroupLayout btnListvisiteLayout = new javax.swing.GroupLayout(btnListvisite);
        btnListvisite.setLayout(btnListvisiteLayout);
        btnListvisiteLayout.setHorizontalGroup(
            btnListvisiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListvisiteLayout.createSequentialGroup()
                .addComponent(pane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel16)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnListvisiteLayout.setVerticalGroup(
            btnListvisiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListvisiteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addContainerGap())
        );

        jPanel1.add(btnListvisite, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 180, -1));

        btnListbatiment.setBackground(new java.awt.Color(0, 51, 51));
        btnListbatiment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListbatimentMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListbatimentMousePressed(evt);
            }
        });

        pane4.setPreferredSize(new java.awt.Dimension(5, 0));

        javax.swing.GroupLayout pane4Layout = new javax.swing.GroupLayout(pane4);
        pane4.setLayout(pane4Layout);
        pane4Layout.setHorizontalGroup(
            pane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pane4Layout.setVerticalGroup(
            pane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons8-list-16.png"))); // NOI18N
        jLabel17.setText("Liste Batiment");

        javax.swing.GroupLayout btnListbatimentLayout = new javax.swing.GroupLayout(btnListbatiment);
        btnListbatiment.setLayout(btnListbatimentLayout);
        btnListbatimentLayout.setHorizontalGroup(
            btnListbatimentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListbatimentLayout.createSequentialGroup()
                .addComponent(pane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel17)
                .addGap(0, 39, Short.MAX_VALUE))
        );
        btnListbatimentLayout.setVerticalGroup(
            btnListbatimentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListbatimentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addContainerGap())
        );

        jPanel1.add(btnListbatiment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 283, -1, -1));

        btnListcellule.setBackground(new java.awt.Color(0, 51, 51));
        btnListcellule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListcelluleMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListcelluleMousePressed(evt);
            }
        });

        pane5.setPreferredSize(new java.awt.Dimension(5, 0));

        javax.swing.GroupLayout pane5Layout = new javax.swing.GroupLayout(pane5);
        pane5.setLayout(pane5Layout);
        pane5Layout.setHorizontalGroup(
            pane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pane5Layout.setVerticalGroup(
            pane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons8-crafting-table-16.png"))); // NOI18N
        jLabel18.setText("Liste Cellule");

        javax.swing.GroupLayout btnListcelluleLayout = new javax.swing.GroupLayout(btnListcellule);
        btnListcellule.setLayout(btnListcelluleLayout);
        btnListcelluleLayout.setHorizontalGroup(
            btnListcelluleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListcelluleLayout.createSequentialGroup()
                .addComponent(pane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel18)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnListcelluleLayout.setVerticalGroup(
            btnListcelluleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListcelluleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addContainerGap())
        );

        jPanel1.add(btnListcellule, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 327, 180, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/B2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 26, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(java.awt.Color.orange);
        jLabel2.setText("PCG");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 26, -1, 55));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 180, 550));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 730, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
       
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseDragged

    private void btnDashbordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashbordMousePressed
        pane1.setBackground(paseClick);
        pane2.setBackground(pasedefault);
        pane3.setBackground(pasedefault);
        pane4.setBackground(pasedefault);
        pane5.setBackground(pasedefault);
        
    }//GEN-LAST:event_btnDashbordMousePressed

    private void btnListdetenueMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListdetenueMousePressed
        pane2.setBackground(paseClick);
        pane1.setBackground(pasedefault);
        pane3.setBackground(pasedefault);
        pane4.setBackground(pasedefault);
        pane5.setBackground(pasedefault);
    }//GEN-LAST:event_btnListdetenueMousePressed

    private void btnDashbordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashbordMouseClicked
        jDesktopPane1.removeAll();
        Dashbord dash = new Dashbord();
        jDesktopPane1.add(dash).setVisible(true);
    }//GEN-LAST:event_btnDashbordMouseClicked

    private void btnListdetenueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListdetenueMouseClicked
        jDesktopPane1.removeAll();
        Listedetenue det = new Listedetenue();
        jDesktopPane1.add(det).setVisible(true);
    }//GEN-LAST:event_btnListdetenueMouseClicked

    private void btnListvisiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListvisiteMouseClicked
        jDesktopPane1.removeAll();
        Listevisite1 det = new Listevisite1();
        jDesktopPane1.add(det).setVisible(true);
    }//GEN-LAST:event_btnListvisiteMouseClicked

    private void btnListvisiteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListvisiteMousePressed
        pane3.setBackground(paseClick);
        pane1.setBackground(pasedefault);
        pane4.setBackground(pasedefault);
        pane2.setBackground(pasedefault);
        pane5.setBackground(pasedefault);
    }//GEN-LAST:event_btnListvisiteMousePressed

    private void btnListbatimentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListbatimentMouseClicked
        jDesktopPane1.removeAll();
        Listebatiment1 det = new Listebatiment1();
        jDesktopPane1.add(det).setVisible(true);
    }//GEN-LAST:event_btnListbatimentMouseClicked

    private void btnListbatimentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListbatimentMousePressed
        pane4.setBackground(paseClick);
        pane1.setBackground(pasedefault);
        pane3.setBackground(pasedefault);
        pane2.setBackground(pasedefault);
        pane5.setBackground(pasedefault);
    }//GEN-LAST:event_btnListbatimentMousePressed

    private void btnListcelluleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListcelluleMouseClicked
       jDesktopPane1.removeAll();
        Listecellule1 det = new Listecellule1();
        jDesktopPane1.add(det).setVisible(true);
    }//GEN-LAST:event_btnListcelluleMouseClicked

    private void btnListcelluleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListcelluleMousePressed
        pane5.setBackground(paseClick);
        pane1.setBackground(pasedefault);
        pane3.setBackground(pasedefault);
        pane2.setBackground(pasedefault);
        pane4.setBackground(pasedefault);
    }//GEN-LAST:event_btnListcelluleMousePressed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked

        Login d = new Login();
        d.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnDashbord;
    private javax.swing.JPanel btnListbatiment;
    private javax.swing.JPanel btnListcellule;
    private javax.swing.JPanel btnListdetenue;
    private javax.swing.JPanel btnListvisite;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lab_date;
    private javax.swing.JLabel lab_heure;
    private javax.swing.JPanel pane1;
    private javax.swing.JPanel pane2;
    private javax.swing.JPanel pane3;
    private javax.swing.JPanel pane4;
    private javax.swing.JPanel pane5;
    // End of variables declaration//GEN-END:variables
}
