/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controlleur.BatimentImplementeDAO;
import Modele.Batimentc;
import java.util.List;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel
 */
public final class Listebatiment1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Listebatiment1
     */
    Controlleur.RepportClass print=new Controlleur.RepportClass();
    public Listebatiment1() {
        initComponents();
        Load_Table();
        // Masquer la bordure en définissant une bordure vide
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        // Supprimer la barre de titre
        BasicInternalFrameUI bui = (BasicInternalFrameUI) getUI();
        bui.setNorthPane(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListeBatiment = new javax.swing.JTable();
        btnPrint = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(730, 510));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 730, 13));

        jButton3.setBackground(new java.awt.Color(0, 51, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("+ Creer Nouveau");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons8-list-20 (1).png"))); // NOI18N
        jLabel16.setText("Liste des Batiment");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 12, -1, -1));

        ListeBatiment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nom", "Capacite", "Date de creation"
            }
        ));
        ListeBatiment.setGridColor(new java.awt.Color(102, 102, 102));
        ListeBatiment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListeBatimentMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ListeBatiment);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 700, 360));

        btnPrint.setBackground(new java.awt.Color(255, 255, 255));
        btnPrint.setForeground(new java.awt.Color(0, 51, 51));
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons8-print-16.png"))); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel2.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Batiment d = new Batiment();
        d.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    int id;
    private void ListeBatimentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListeBatimentMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ListeBatimentMouseClicked

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        print.listebatiment();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintActionPerformed

    public void Load_Table() {
        BatimentImplementeDAO bl = new BatimentImplementeDAO();
        List<Batimentc> List = bl.list();
        DefaultTableModel df = (DefaultTableModel) ListeBatiment.getModel();
        df.setRowCount(0);
        
        List.forEach((b) -> {
            df.addRow(new Object[]{
                b.getId(),
                b.getDesignation(),
                b.getNombreCellule(),
                b.getDate_de_construction()
            });
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ListeBatiment;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
